In [1]:
import pandas as pd

In [2]:
from sklearn.ensemble import RandomForestClassifier

In [3]:
data = pd.read_excel("irisTrain.xlsx")
data.head()

   sepallength  sepalwidth  petallength  petalwidth           class
0          7.9         3.8          6.4         2.0  Iris-virginica
1          7.7         3.8          6.7         2.2  Iris-virginica
2          7.7         3.0          6.1         2.3  Iris-virginica
3          7.7         2.8          6.7         2.0  Iris-virginica
4          7.7         2.6          6.9         2.3  Iris-virginica

In [4]:
x= data.iloc[:,:-1]

In [5]:
x

     sepallength  sepalwidth  petallength  petalwidth
0            7.9         3.8          6.4         2.0
1            7.7         3.8          6.7         2.2
2            7.7         3.0          6.1         2.3
3            7.7         2.8          6.7         2.0
4            7.7         2.6          6.9         2.3
..           ...         ...          ...         ...
111          4.5         2.3          1.3         0.3
112          4.4         3.2          1.3         0.2
113          4.4         3.0          1.3         0.2
114          4.4         2.9          1.4         0.2
115          4.3         3.0          1.1         0.1

[116 rows x 4 columns]

In [6]:
y= data.iloc[:,-1]

In [7]:
y

0      Iris-virginica
1      Iris-virginica
2      Iris-virginica
3      Iris-virginica
4      Iris-virginica
            ...
111       Iris-setosa
112       Iris-setosa
113       Iris-setosa
114       Iris-setosa
115       Iris-setosa
Name: class, Length: 116, dtype: object

In [8]:
model=RandomForestClassifier()

In [9]:
model.fit(x.values,y.values)

RandomForestClassifier()

In [10]:
prediction= model.predict([[5.4, 3 , 5.6, 1.5]])

In [11]:
prediction

array(['Iris-virginica'], dtype=object)

In [12]:
dataTest = pd.read_excel("irisTest.xlsx")

In [13]:
x_test= dataTest.iloc[:,:-1]

In [14]:
x_test.values

array([[5.4, 3. , 4.5, 1.5],
       [5.3, 3.7, 1.5, 0.2],
       [5.2, 4.1, 1.5, 0.1],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [5.2, 2.7, 3.9, 1.4],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 3.8, 1.6, 0.2],
       [5.1, 3.8, 1.5, 0.3],
       [5.1, 3.7, 1.5, 0.4],
       [5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.3],
       [5.1, 3.4, 1.5, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.1, 2.5, 3. , 1.1],
       [5. , 3.6, 1.4, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5. , 3.5, 1.3, 0.3],
       [5. , 3.4, 1.6, 0.4],
       [5. , 3.4, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 2.3, 3.3, 1. ],
       [5. , 2. , 3.5, 1. ],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 3. , 1.4, 0.2],
       [4.9, 2.5, 4.5, 1.7],
       [4.9, 2.4, 3.3, 1. ],
       [4.8, 3.4, 1.9, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2]])

In [15]:
predictions= model.predict(x_test.values)

In [16]:
predictions

array(['Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa'], dtype=object)

In [17]:
actual=  dataTest.iloc[:,-1]

In [19]:
actual.values

array(['Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa'], dtype=object)

In [24]:
count=0
for i in range(0, len(actual)):
    if predictions[i]== actual[i]:
        count= count + 1

accuracy= count/actual(len) *100
print(accuracy)

TypeError: 'Series' object is not callable